#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors

Configuration for Gorge Chase PPO.
"""


class Config:
    HERO_FEATURE_DIM = 5
    MONSTER_FEATURE_DIM = 5
    TARGET_FEATURE_DIM = 4
    OBSTACLE_FEATURE_DIM = 12
    MOTION_FEATURE_DIM = 6
    LOCAL_MAP_SIZE = 21
    LOCAL_MAP_DIM = LOCAL_MAP_SIZE * LOCAL_MAP_SIZE
    LEGAL_ACTION_DIM = 16
    PROGRESS_FEATURE_DIM = 7

    # Feature layout:
    # hero(5) + monster1(5) + monster2(5) + nearest_treasure(4) + nearest_buff(4)
    # + obstacle_context(12) + motion_context(6) + local_map(21x21=441)
    # + legal_action(16) + progress(7)
    FEATURES = [
        HERO_FEATURE_DIM,
        MONSTER_FEATURE_DIM,
        MONSTER_FEATURE_DIM,
        TARGET_FEATURE_DIM,
        TARGET_FEATURE_DIM,
        OBSTACLE_FEATURE_DIM,
        MOTION_FEATURE_DIM,
        LOCAL_MAP_DIM,
        LEGAL_ACTION_DIM,
        PROGRESS_FEATURE_DIM,
    ]
    FEATURE_SPLIT_SHAPE = FEATURES
    FEATURE_LEN = sum(FEATURE_SPLIT_SHAPE)
    DIM_OF_OBSERVATION = FEATURE_LEN
    LOCAL_MAP_GROUP_INDEX = 7

    # 8 movement directions + 8 flash directions.
    ACTION_NUM = 16

    VALUE_NUM = 1

    GAMMA = 0.99
    LAMDA = 0.95
    INIT_LEARNING_RATE_START = 0.0003
    BETA_START = 0.012
    BETA_END = 0.004
    BETA_DECAY_STEPS = 20000
    CLIP_PARAM = 0.2
    VF_COEF = 1.0
    GRAD_CLIP_RANGE = 0.5

    SURVIVAL_STEP_REWARD = 0.0
    SURVIVAL_REWARD_DECAY_START = 0.55
    SURVIVAL_REWARD_MIN_SCALE = 0.05
    DANGER_SHAPING_COEF = 0.12
    TREASURE_SHAPING_COEF = 0.0
    SAFE_TREASURE_SHAPING_COEF = 0.0
    BUFF_SHAPING_COEF = 0.0
    BUFF_DANGER_SHAPING_COEF = 0.0
    TREASURE_PICKUP_BONUS = 0.0
    BUFF_PICKUP_BONUS = 0.0
    COLLECTION_STREAK_BONUS = 0.0
    MAX_COLLECTION_STREAK_BONUS = 3
    TERMINAL_CAUGHT_PENALTY = -3.0
    TERMINAL_SURVIVE_BONUS = 1.0

    WALL_COLLISION_PENALTY = -0.10
    STUCK_STATIONARY_PENALTY_COEF = 0.0
    STUCK_REPEAT_PENALTY_COEF = 0.0
    STUCK_DANGER_MULTIPLIER = 2.0
    STUCK_PENALTY_CAP = 0.50
    LOOP_REVISIT_WINDOW = 8
    LOOP_REVISIT_DISTANCE = 2.5
    LOOP_REVISIT_PENALTY_COEF = 0.0
    LOOP_REVISIT_PENALTY_CAP = 0.08
    LOOP_CONFINED_MULTIPLIER = 1.5
    WALL_REPULSION_THRESHOLD = 0.30
    WALL_REPULSION_COEF = 0.0

    FLASH_ESCAPE_BONUS_BASE = 0.0
    FLASH_ESCAPE_BONUS_GAIN_COEF = 0.0
    FLASH_SURVIVAL_BONUS_BASE = 0.0
    FLASH_SURVIVAL_BONUS_GAIN_COEF = 0.0
    FLASH_SURVIVAL_BONUS_MAX = 0.0
    FLASH_WASTE_BLOCKED_PENALTY = 0.0
    FLASH_WASTE_SAFE_PENALTY = 0.0
    FLASH_WASTE_BAD_GAIN_PENALTY = 0.0

    PREDICTIVE_DANGER_DIST_NORM = 0.18
    PREDICTIVE_DANGER_PENALTY_COEF = 0.0
    PREDICTIVE_DANGER_PENALTY_CAP = 0.0
    PREDICTIVE_MONSTER_HORIZONS = (1, 2, 3)
    PREDICTIVE_DANGER_STAGE1_SCALE = 0.40
    PREDICTIVE_DANGER_STAGE2_SCALE = 0.70
    PREDICTIVE_DANGER_STAGE3_SCALE = 1.00

    CURRICULUM_TOTAL_EPISODES = 100000
    CURRICULUM_STAGE1_RATIO = 0.30
    CURRICULUM_STAGE2_RATIO = 0.70
    CURRICULUM_STAGE1_MONSTER_SPEED_SCALE = 0.50
    CURRICULUM_STAGE2_MONSTER_SPEED_SCALE = 0.80
    CURRICULUM_STAGE3_MONSTER_SPEED_SCALE = 1.00
    CURRICULUM_STAGE1_MONSTER_INTERVAL_SCALE = 2.00
    CURRICULUM_STAGE2_MONSTER_INTERVAL_SCALE = 1.50
    CURRICULUM_STAGE3_MONSTER_INTERVAL_SCALE = 1.00
